### ISSUE TITLE
[Bug]: Identify command returning 401

### ISSUE THREAD

**Issue by SCBmbry** [hackthebox/Hackster#130]
### Describe the bug

Identify command receiving a 401 response code with the default HTB_API_SECRET from .test.env.

### To reproduce

Fill required values in .env, use default values for other variables, run the bot

### Expected behavior

Receive a json response from a proper identifier input

### Relevant log output

```shell
AttributeError: 'NoneType' object has no attribute 'send'
12:35:21 - src.helpers.verification ERROR: Non-OK HTTP status code returned from identifier lookup: 401.
12:35:22 - src.bot DEBUG: Command 'identify' completed.
```

**Comment by janssensjelle** [comment]
@SCBmbry not exactly sure what you're expecting but this command and the process of verification isn't public IIRC. A `401` status code means that you're unauthorised to perform this action. The token in the `.test.env` is a dummy one. So, not getting a json response seems correct to me

**Comment by SCBmbry** [comment]
@janssensjelle thank you for the clarity, that was the answer I had expected. As I had not seen it explicitly documented anywhere, I could not be sure.
