### ISSUE TITLE
[Bug]: Notes not added on kick/ban

### ISSUE THREAD

**Issue by 0xEmma** [hackthebox/Hackster#20]
### Describe the bug

When banning a user, or kicking a user it doesnt show in ++history

### To reproduce

ban/kick a user
run history on said user
nothing

### Expected behavior

ban/kick a user
run history on said user
shows ban / kick + reason

**Comment by dimoschi** [comment]
This was fixed for bug in PR #19. For kick command nothing was added to the history, so I don't consider this a bug.

**Comment by 0xEmma** [comment]
@dimoschi a simple note record should be added just for future reference, "Kicked on {date} for reason"
