### ISSUE TITLE
[Bug]: `whois` does not accept non-Discord IDs

### ISSUE THREAD

**Issue by clubby789** [hackthebox/Hackster#24]
### Describe the bug

The `/whois` command can take either a Discord or HTB ID and retrieve the corresponding linked account. Because the paramater is typed as a `Member` though, the client does not allow entering numbers such as a HTB ID
https://github.com/hackthebox/Hackster/blob/main/src/cmds/core/user.py#L191
So only the Discord -> HTB lookup works

### To reproduce

1. Type `/whois`
2. Fill the user field with a HTB ID (`83743`)

### Expected behavior

I expected that I'd see my Discord account linked
Instead, I saw this error
![image](https://user-images.githubusercontent.com/13556931/237025797-d711abdf-0611-4502-a40c-c5a1c5792c5e.png)

**Comment by dimoschi** [comment]
I don't like having an argument `user` that can take both a `Member` and an HTB `user_id`, so I'm gonna convert the `user` to optional and will add a second argument called `htb_id`. What do you think about it?
