### ISSUE TITLE
Error after setting environment variables and starting the bot

### ISSUE THREAD

**Issue by tissy9491** [hackthebox/Hackster#29]
### Describe the bug

After I setup the env variables with `export` command, and launching `poetry run task start`, I get this error: https://pastebin.com/gjNtv0g8

What did I do wrong? Did I miss something?
Thanks for your time and your help.

### To reproduce

---

### Expected behavior

---

**Comment by dimoschi** [comment]
@tissy9491 you need a running MariaDB (or MySQL) server to start the bot. We will provide in a future update a docker-compose that will spin up all parts required, so stay tuned or you can create a PR to add that functionality.
