### ISSUE TITLE
[Feature]: APT Joining

### ISSUE THREAD

**Issue by 0xEmma** [hackthebox/Hackster#30]
### Describe the solution you'd like

We had intended to add this into the old bot but had never gotten around to it

## The Apt role has the following requirements:
- Three month Discord membership requirement
- Message count greater than 1000
- No current warnings or strikes

## When a user runs /join APT the bot should:
- Ensure joined 3 months ago
- Ensure over 1000 messages
- Ensure no warnings / strikes issued within the last 14 days

If these are met, grant the APT role, and inform the user: "You've been designated an APT 😎"

### If not, inform the user as of why:
Example error:
`We're sorry, but you are not eligible for the APT Role. You have 525/1000 needed messages`
`We're sorry, but you are not eligible for the APT Role. You joined less then 3 months ago. Retry on {DATE}`
`We're sorry, but you are not eligible for the APT Role. You have been issued a warning/strike within the last 14 days.`

## When a user is warned:
- Check for the presence of the APT role
If they have it, remove it and add to the warn message that is has been removed and they can re-request it in 14 days

**Comment by daanbreur** [comment]
Good idea. However, shouldn't there be a way to manually overwrite it without giving a strike/warning?

**Comment by 0xEmma** [comment]
> Good idea. However, shouldn't there be a way to manually overwrite it without giving a strike/warning? And what about the joining, you could have rejoined lately and the bot won't know that (I think)?

It can be removed manually, but would involve creating a blacklist so they can't just re-add it. 

While useful, that involves storing extra data for use-case i don't think we've ever had a need for. We can re-evaluate the need for such a thing post-release

**Comment by daanbreur** [comment]
Fair, what about the rejoining?

**Comment by HeckerBirb** [comment]
Tip: there's already code that determines if an infraction is active which should be used here too, instead of hard coded number.
