### ISSUE TITLE
[Bug]: Temp ban - Application did not respond

### ISSUE THREAD

**Issue by ToxicBiohazard** [hackthebox/Hackster#32]
### Describe the bug

Tempban command execution works as per audit log, but it returns Application did not respond

### To reproduce

Use the command `/tempban user:@Tejas#4422 duration:6Mo reason:Testing`

### Expected behavior

It should output 561210274653274133 has been banned until 2024-08-16 15:13:16 (UTC) and ban the user, also add note for the same. 

### Relevant log output

![image](https://github.com/hackthebox/Hackster/assets/98106526/ed79496d-713d-46ab-b0ce-ed5828ade89e)

![image](https://github.com/hackthebox/Hackster/assets/98106526/b5cdaf86-878c-4132-8c40-9f755550fa25)

**Comment by ToxicBiohazard** [comment]
@dimoschi  Infraction with the reason and duration.

**Comment by 0xEmma** [comment]
was fixed in latest release
