### ISSUE TITLE
[Feature]: Ability for Fugl to ping "Noah Gang"

### ISSUE THREAD

**Issue by HeckerBirb** [hackthebox/Hackster#34]
### Describe the solution you'd like

Noah pics have stalled since I cannot ping the Noah Gang role. Sadge.
Requesting ability to ping "Noah Gang". 🥲

### Is your feature request related to a problem?

Cannot ping "Noah Gang".

**Comment by daanbreur** [comment]
Very urgent issue. Would be amazing if someone made a PR for this.

**Comment by 0xEmma** [comment]
See comment in #39
